# Generated by Django 6.0.1 on 2026-01-11 16:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex: Administrativo (Seg-Sex), Escala 12x36', max_length=50, unique=True)),
                ('carga_horaria_diaria', models.DurationField(default=datetime.timedelta(seconds=28800), help_text='Carga horária padrão (Ex: 08:00:00)')),
                ('trabalha_segunda', models.BooleanField(default=True)),
                ('trabalha_terca', models.BooleanField(default=True)),
                ('trabalha_quarta', models.BooleanField(default=True)),
                ('trabalha_quinta', models.BooleanField(default=True)),
                ('trabalha_sexta', models.BooleanField(default=True)),
                ('trabalha_sabado', models.BooleanField(default=False)),
                ('trabalha_domingo', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_dom',
            field=models.BooleanField(default=False, verbose_name='Indiv. Domingo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_qua',
            field=models.BooleanField(default=True, verbose_name='Indiv. Quarta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_qui',
            field=models.BooleanField(default=True, verbose_name='Indiv. Quinta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_sab',
            field=models.BooleanField(default=False, verbose_name='Indiv. Sábado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_seg',
            field=models.BooleanField(default=True, verbose_name='Indiv. Segunda'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_sex',
            field=models.BooleanField(default=True, verbose_name='Indiv. Sexta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='trab_ter',
            field=models.BooleanField(default=True, verbose_name='Indiv. Terça'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usar_configuracao_individual',
            field=models.BooleanField(default=False, help_text='Se marcado, ignora a Escala e usa os dias abaixo.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carga_horaria_diaria',
            field=models.DurationField(blank=True, help_text='Ex: 08:00:00. Se vazio, usa a da Escala.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.escala'),
        ),
    ]
