# Generated by Django 6.0.1 on 2026-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escala_usuario_trab_dom_usuario_trab_qua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_inicio_apuracao',
            field=models.DateField(blank=True, help_text='Data inicial para cálculo do Banco de Horas. Registros anteriores a esta data serão ignorados.', null=True),
        ),
    ]
