# Generated by Django 6.0.1 on 2026-01-12 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_data_inicio_apuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('nome', models.CharField(help_text='Ex: Natal, Consciência Negra', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='core.empresa')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('empresa', 'data')},
            },
        ),
    ]
