# Generated by Django 6.0.1 on 2026-01-13 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feriado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex: Recesso de Fim de Ano, Férias Coletivas', max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recessos', to='core.empresa')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
    ]
